# Generated by Django 2.1.5 on 2019-01-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("checks", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(name="datacheck", options={"ordering": ("-pk",)}),
        migrations.AlterField(
            model_name="checkrun",
            name="result",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Success"),
                    ("WARNING", "Warning"),
                    ("FAILED", "Failed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
