# Generated by Django 2.1.4 on 2018-12-06 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_auto_20181205_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkrun',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkrun',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
