# Generated by Django 2.1.4 on 2018-12-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0003_auto_20181206_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkrun',
            name='left_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkrun',
            name='right_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkrun',
            name='warning_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
