# Generated by Django 2.1.5 on 2019-01-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0004_auto_20181206_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkrun',
            name='result',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('FAILED', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='environmentstatus',
            name='result',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('FAILED', 'Failed')], max_length=20),
        ),
    ]
