default_language_version:
  python: python3.7
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
#  -   repo: https://github.com/pre-commit/mirrors-pylint
#      rev: v2.4.2
#      hooks:
#        - id: pylint
#          additional_dependencies: [pylint-django, pylint-celery]
