orbs:
  docker: circleci/docker@0.5.17
version: 2.1
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          dockerfile: compose/master/inspector/Dockerfile
          image: $DOCKER_IMAGE_NAME
          tag: $CIRCLE_BRANCH
