# Generated by Django 2.1.4 on 2018-12-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='user',
            new_name='login',
        ),
    ]
