# Generated by Django 2.2.6 on 2019-10-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("systems", "0002_auto_20190324_1733")]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="extra_json",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="system",
            name="application",
            field=models.IntegerField(
                choices=[
                    (0, "Postgresql"),
                    (1, "Redshift"),
                    (2, "MySQL"),
                    (3, "Snowflake"),
                ]
            ),
        ),
    ]
