# Generated by Django 2.2.7 on 2019-11-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("systems", "0003_auto_20191030_1352")]

    operations = [
        migrations.RenameField(
            model_name="instance", old_name="database_or_schema", new_name="db"
        )
    ]
