# Generated by Django 2.1.5 on 2019-01-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0005_auto_20190115_1523'),
        ('systems', '0003_auto_20181206_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Environment',
            new_name='Environment',
        ),
    ]
