# Generated by Django 2.2.7 on 2019-11-12 11:38

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [("systems", "0004_auto_20191111_1612")]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="schema",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="instance",
            name="db",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="instance",
            name="host",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="instance",
            name="login",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="instance",
            name="password",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="port",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
