# Database only

version: '3'

services:

  postgres:
    image: postgres:12
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ../.envs/.develop/.postgres
    ports:
      - 5432:5432

  redis:
    image: redis:5
    ports:
      - 6379:6379

volumes:
  pgdata:
